[tool.poetry]
name = "py-chinese-pornounce"
version = "0.1.0"
description = ""
authors = ["Philip Huang <p208p2002@gmail.com>"]
include = ["py_chinese_pornounce/*.txt"]

[tool.poetry.dependencies]
python = "^3.7"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
